version: "3.8"
services:

  sample_db:
    # image: mysql:8.2.0
    image: nyankopunch/statscast-mysql-loader:v2.0
    container_name: sample_db
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql/sql:/docker-entrypoint-initdb.d # 自動でテーブルを作成する場合
      # - ./mysql/data:/work # 手動でテーブルを作成する場合
      # - ./mysql/conf.d:/etc/mysql/conf.d
    ports:
      - 3306:3306

  bi:
    image: bi
    container_name: bi
    environment:
      - MYSQL_HOST=sample_db
      - MYSQL_PORT=3306
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=mydatabase
    ports:
      - 8501:8501
    volumes:
      - type: bind
        source: ./bi/src
        target: /src
    depends_on:
      - sample_db
    
  jupyter:
    container_name: jupyter
    build:
      context: ./jupyter
      dockerfile: Dockerfile
    environment: 
      JUPYTER_TOKEN : ''
      MYSQL_HOST: sample_db
      MYSQL_PORT: 3306
      MYSQL_USER: myuser
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: mydatabase
    ports:
      - 8888:8888
    volumes:
      - type: bind
        source: ./jupyter/work
        target: /home/jovyan/work
    command: start.sh jupyter lab --NotebookApp.token=''
    depends_on:
      - sample_db

# version: '3.8'
# services:
#   panel-app:
#     build:
#       context: .
#       dockerfile: Dockerfile
#     ports:
#       - "5006:5006"
#     volumes:
#       - ./src:/work/src
#     command: ["panel", "serve", "--port", "5006", "src/app4.py", "--autoreload"]

  